# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x10maibot.plugin.v2\"\xf6\x01\n\rRunnerMessage\x12/\n\x05hello\x18\x01 \x01(\x0b\x32\x1e.maibot.plugin.v2.HelloPayloadH\x00\x12/\n\x05\x65vent\x18\x02 \x01(\x0b\x32\x1e.maibot.plugin.v2.EventPayloadH\x00\x12\x38\n\theartbeat\x18\x03 \x01(\x0b\x32#.maibot.plugin.v2.HeartbeatResponseH\x00\x12>\n\rgateway_ready\x18\x04 \x01(\x0b\x32%.maibot.plugin.v2.GatewayReadyPayloadH\x00\x42\t\n\x07payload\"\xf4\x01\n\x0bHostMessage\x12\x39\n\x0ehello_response\x18\x01 \x01(\x0b\x32\x1f.maibot.plugin.v2.HelloResponseH\x00\x12/\n\tevent_ack\x18\x02 \x01(\x0b\x32\x1a.maibot.plugin.v2.EventAckH\x00\x12\x37\n\theartbeat\x18\x03 \x01(\x0b\x32\".maibot.plugin.v2.HeartbeatRequestH\x00\x12\x35\n\x08shutdown\x18\x04 \x01(\x0b\x32!.maibot.plugin.v2.ShutdownRequestH\x00\x42\t\n\x07payload\"|\n\x0cHelloPayload\x12\x11\n\trunner_id\x18\x01 \x01(\t\x12\x13\n\x0bsdk_version\x18\x02 \x01(\t\x12\x15\n\rsession_token\x18\x03 \x01(\t\x12\x0e\n\x06scopes\x18\x04 \x03(\t\x12\x1d\n\x15runner_listen_address\x18\x05 \x01(\t\"`\n\rHelloResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x14\n\x0chost_version\x18\x02 \x01(\t\x12\x0e\n\x06reason\x18\x03 \x01(\t\x12\x17\n\x0frejected_scopes\x18\x04 \x03(\t\"(\n\x10HeartbeatRequest\x12\x14\n\x0ctimestamp_ms\x18\x01 \x01(\x03\")\n\x11HeartbeatResponse\x12\x14\n\x0ctimestamp_ms\x18\x01 \x01(\x03\";\n\x0fShutdownRequest\x12\x0e\n\x06reason\x18\x01 \x01(\t\x12\x18\n\x10\x64rain_timeout_ms\x18\x02 \x01(\x05\"3\n\x0c\x45ventPayload\x12\x12\n\nevent_name\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t\"\x1c\n\x08\x45ventAck\x12\x10\n\x08received\x18\x01 \x01(\x08\"o\n\x13GatewayReadyPayload\x12\x14\n\x0cgateway_name\x18\x01 \x01(\t\x12\x10\n\x08platform\x18\x02 \x01(\t\x12\r\n\x05ready\x18\x03 \x01(\x08\x12\x12\n\naccount_id\x18\x04 \x01(\t\x12\r\n\x05scope\x18\x05 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RUNNERMESSAGE']._serialized_start=35
  _globals['_RUNNERMESSAGE']._serialized_end=281
  _globals['_HOSTMESSAGE']._serialized_start=284
  _globals['_HOSTMESSAGE']._serialized_end=528
  _globals['_HELLOPAYLOAD']._serialized_start=530
  _globals['_HELLOPAYLOAD']._serialized_end=654
  _globals['_HELLORESPONSE']._serialized_start=656
  _globals['_HELLORESPONSE']._serialized_end=752
  _globals['_HEARTBEATREQUEST']._serialized_start=754
  _globals['_HEARTBEATREQUEST']._serialized_end=794
  _globals['_HEARTBEATRESPONSE']._serialized_start=796
  _globals['_HEARTBEATRESPONSE']._serialized_end=837
  _globals['_SHUTDOWNREQUEST']._serialized_start=839
  _globals['_SHUTDOWNREQUEST']._serialized_end=898
  _globals['_EVENTPAYLOAD']._serialized_start=900
  _globals['_EVENTPAYLOAD']._serialized_end=951
  _globals['_EVENTACK']._serialized_start=953
  _globals['_EVENTACK']._serialized_end=981
  _globals['_GATEWAYREADYPAYLOAD']._serialized_start=983
  _globals['_GATEWAYREADYPAYLOAD']._serialized_end=1094
# @@protoc_insertion_point(module_scope)
