# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: plugin_runner.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'plugin_runner.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from src.plugin_runtime_v2.proto import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13plugin_runner.proto\x12\x10maibot.plugin.v2\x1a\x0c\x63ommon.proto\"H\n\x11InvokeToolRequest\x12\x11\n\ttool_name\x18\x01 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x01(\t\x12\x12\n\ntimeout_ms\x18\x03 \x01(\x05\"D\n\x12InvokeToolResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06result\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t2g\n\x0cPluginRunner\x12W\n\nInvokeTool\x12#.maibot.plugin.v2.InvokeToolRequest\x1a$.maibot.plugin.v2.InvokeToolResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plugin_runner_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INVOKETOOLREQUEST']._serialized_start=55
  _globals['_INVOKETOOLREQUEST']._serialized_end=127
  _globals['_INVOKETOOLRESPONSE']._serialized_start=129
  _globals['_INVOKETOOLRESPONSE']._serialized_end=197
  _globals['_PLUGINRUNNER']._serialized_start=199
  _globals['_PLUGINRUNNER']._serialized_end=302
# @@protoc_insertion_point(module_scope)
