# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: plugin_host.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'plugin_host.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from src.plugin_runtime_v2.proto import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11plugin_host.proto\x12\x10maibot.plugin.v2\x1a\x0c\x63ommon.proto\"f\n\x0fToolDeclaration\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x19\n\x11parameters_schema\x18\x03 \x01(\t\x12\x15\n\routput_schema\x18\x04 \x01(\t\"K\n\x10\x45ventDeclaration\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x14\n\x0c\x65vent_schema\x18\x03 \x01(\t\"\xac\x01\n\x19RegisterComponentsRequest\x12\x11\n\tplugin_id\x18\x01 \x01(\t\x12\x16\n\x0eplugin_version\x18\x02 \x01(\t\x12\x30\n\x05tools\x18\x03 \x03(\x0b\x32!.maibot.plugin.v2.ToolDeclaration\x12\x32\n\x06\x65vents\x18\x04 \x03(\x0b\x32\".maibot.plugin.v2.EventDeclaration\"?\n\x1aRegisterComponentsResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x0f\n\x07reasons\x18\x02 \x03(\t2\xcc\x01\n\nPluginHost\x12M\n\x07\x43onnect\x12\x1f.maibot.plugin.v2.RunnerMessage\x1a\x1d.maibot.plugin.v2.HostMessage(\x01\x30\x01\x12o\n\x12RegisterComponents\x12+.maibot.plugin.v2.RegisterComponentsRequest\x1a,.maibot.plugin.v2.RegisterComponentsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plugin_host_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOOLDECLARATION']._serialized_start=53
  _globals['_TOOLDECLARATION']._serialized_end=155
  _globals['_EVENTDECLARATION']._serialized_start=157
  _globals['_EVENTDECLARATION']._serialized_end=232
  _globals['_REGISTERCOMPONENTSREQUEST']._serialized_start=235
  _globals['_REGISTERCOMPONENTSREQUEST']._serialized_end=407
  _globals['_REGISTERCOMPONENTSRESPONSE']._serialized_start=409
  _globals['_REGISTERCOMPONENTSRESPONSE']._serialized_end=472
  _globals['_PLUGINHOST']._serialized_start=475
  _globals['_PLUGINHOST']._serialized_end=679
# @@protoc_insertion_point(module_scope)
