# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: plugin_config.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'plugin_config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13plugin_config.proto\x12\x11plugin_runtime_v2\"e\n\x19UpdatePluginConfigRequest\x12\x11\n\tplugin_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63onfig_json\x18\x02 \x01(\t\x12\x10\n\x08revision\x18\x03 \x01(\x05\x12\x0e\n\x06source\x18\x04 \x01(\t\"R\n\x1aUpdatePluginConfigResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\x14\n\x0cnew_revision\x18\x03 \x01(\x05\x32\x88\x01\n\x13PluginConfigService\x12q\n\x12UpdatePluginConfig\x12,.plugin_runtime_v2.UpdatePluginConfigRequest\x1a-.plugin_runtime_v2.UpdatePluginConfigResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plugin_config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPDATEPLUGINCONFIGREQUEST']._serialized_start=42
  _globals['_UPDATEPLUGINCONFIGREQUEST']._serialized_end=143
  _globals['_UPDATEPLUGINCONFIGRESPONSE']._serialized_start=145
  _globals['_UPDATEPLUGINCONFIGRESPONSE']._serialized_end=227
  _globals['_PLUGINCONFIGSERVICE']._serialized_start=230
  _globals['_PLUGINCONFIGSERVICE']._serialized_end=366
# @@protoc_insertion_point(module_scope)
