# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.plugin_runtime_v2.proto import common_pb2 as common__pb2
from src.plugin_runtime_v2.proto import plugin_host_pb2 as plugin__host__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in plugin_host_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PluginHostStub:
    """============================================================
    Host 端 gRPC 服务
    ============================================================

    Host 端暴露的 gRPC 服务，Runner 连接后调用
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.stream_stream(
                '/maibot.plugin.v2.PluginHost/Connect',
                request_serializer=common__pb2.RunnerMessage.SerializeToString,
                response_deserializer=common__pb2.HostMessage.FromString,
                _registered_method=True)
        self.RegisterComponents = channel.unary_unary(
                '/maibot.plugin.v2.PluginHost/RegisterComponents',
                request_serializer=plugin__host__pb2.RegisterComponentsRequest.SerializeToString,
                response_deserializer=plugin__host__pb2.RegisterComponentsResponse.FromString,
                _registered_method=True)


class PluginHostServicer:
    """============================================================
    Host 端 gRPC 服务
    ============================================================

    Host 端暴露的 gRPC 服务，Runner 连接后调用
    """

    def Connect(self, request_iterator, context):
        """双向流连接：Runner 通过此流建立持久连接，
        首次消息携带 HelloPayload，后续可推送 EventPayload
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterComponents(self, request, context):
        """组件注册：Runner 上报 Tool 和 Event 声明
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PluginHostServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.stream_stream_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=common__pb2.RunnerMessage.FromString,
                    response_serializer=common__pb2.HostMessage.SerializeToString,
            ),
            'RegisterComponents': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterComponents,
                    request_deserializer=plugin__host__pb2.RegisterComponentsRequest.FromString,
                    response_serializer=plugin__host__pb2.RegisterComponentsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'maibot.plugin.v2.PluginHost', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('maibot.plugin.v2.PluginHost', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PluginHost:
    """============================================================
    Host 端 gRPC 服务
    ============================================================

    Host 端暴露的 gRPC 服务，Runner 连接后调用
    """

    @staticmethod
    def Connect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/maibot.plugin.v2.PluginHost/Connect',
            common__pb2.RunnerMessage.SerializeToString,
            common__pb2.HostMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterComponents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/maibot.plugin.v2.PluginHost/RegisterComponents',
            plugin__host__pb2.RegisterComponentsRequest.SerializeToString,
            plugin__host__pb2.RegisterComponentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
