# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.plugin_runtime_v2.proto import plugin_runner_pb2 as plugin__runner__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in plugin_runner_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PluginRunnerStub:
    """============================================================
    Runner 端 gRPC 服务
    ============================================================

    Runner 端暴露的 gRPC 服务，Host 调用插件功能
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InvokeTool = channel.unary_unary(
                '/maibot.plugin.v2.PluginRunner/InvokeTool',
                request_serializer=plugin__runner__pb2.InvokeToolRequest.SerializeToString,
                response_deserializer=plugin__runner__pb2.InvokeToolResponse.FromString,
                _registered_method=True)


class PluginRunnerServicer:
    """============================================================
    Runner 端 gRPC 服务
    ============================================================

    Runner 端暴露的 gRPC 服务，Host 调用插件功能
    """

    def InvokeTool(self, request, context):
        """Tool 调用：Host 请求 Runner 执行指定 Tool
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PluginRunnerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InvokeTool': grpc.unary_unary_rpc_method_handler(
                    servicer.InvokeTool,
                    request_deserializer=plugin__runner__pb2.InvokeToolRequest.FromString,
                    response_serializer=plugin__runner__pb2.InvokeToolResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'maibot.plugin.v2.PluginRunner', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('maibot.plugin.v2.PluginRunner', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PluginRunner:
    """============================================================
    Runner 端 gRPC 服务
    ============================================================

    Runner 端暴露的 gRPC 服务，Host 调用插件功能
    """

    @staticmethod
    def InvokeTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/maibot.plugin.v2.PluginRunner/InvokeTool',
            plugin__runner__pb2.InvokeToolRequest.SerializeToString,
            plugin__runner__pb2.InvokeToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
