# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import plugin_config_pb2 as plugin__config__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in plugin_config_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PluginConfigServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdatePluginConfig = channel.unary_unary(
                '/plugin_runtime_v2.PluginConfigService/UpdatePluginConfig',
                request_serializer=plugin__config__pb2.UpdatePluginConfigRequest.SerializeToString,
                response_deserializer=plugin__config__pb2.UpdatePluginConfigResponse.FromString,
                _registered_method=True)


class PluginConfigServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def UpdatePluginConfig(self, request, context):
        """Host 推送配置到 Runner → Runner 调用 plugin.on_config_update(new, prev)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PluginConfigServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdatePluginConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePluginConfig,
                    request_deserializer=plugin__config__pb2.UpdatePluginConfigRequest.FromString,
                    response_serializer=plugin__config__pb2.UpdatePluginConfigResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'plugin_runtime_v2.PluginConfigService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('plugin_runtime_v2.PluginConfigService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PluginConfigService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdatePluginConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/plugin_runtime_v2.PluginConfigService/UpdatePluginConfig',
            plugin__config__pb2.UpdatePluginConfigRequest.SerializeToString,
            plugin__config__pb2.UpdatePluginConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
