from enum import Enum


class ErrorCode(str, Enum):
    AUTH_FAILED = "AUTH_FAILED"
    AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
    AUTH_RATE_LIMITED = "AUTH_RATE_LIMITED"
    PARAM_INVALID = "PARAM_INVALID"
    PARAM_CONFIG_INVALID = "PARAM_CONFIG_INVALID"
    PARAM_MISSING = "PARAM_MISSING"
    BIZ_NOT_FOUND = "BIZ_NOT_FOUND"
    BIZ_CONFIG_WRITE_FAILED = "BIZ_CONFIG_WRITE_FAILED"
    BIZ_STATE_CONFLICT = "BIZ_STATE_CONFLICT"
    SYS_INTERNAL_ERROR = "SYS_INTERNAL_ERROR"
    SYS_SERVICE_UNAVAILABLE = "SYS_SERVICE_UNAVAILABLE"


ERROR_CODE_HTTP_STATUS: dict[ErrorCode, int] = {
    ErrorCode.AUTH_FAILED: 401,
    ErrorCode.AUTH_TOKEN_EXPIRED: 401,
    ErrorCode.AUTH_RATE_LIMITED: 429,
    ErrorCode.PARAM_INVALID: 400,
    ErrorCode.PARAM_CONFIG_INVALID: 400,
    ErrorCode.PARAM_MISSING: 400,
    ErrorCode.BIZ_NOT_FOUND: 404,
    ErrorCode.BIZ_CONFIG_WRITE_FAILED: 500,
    ErrorCode.BIZ_STATE_CONFLICT: 409,
    ErrorCode.SYS_INTERNAL_ERROR: 500,
    ErrorCode.SYS_SERVICE_UNAVAILABLE: 503,
}